### ISSUE TITLE
iphone - chrome: Mobile pages not fitting width of page

### ISSUE THREAD

**Issue by c-schooley** [CCI-Studios/Change-the-World#10]
About Page, Organizations page , Youth, Change The World 2016 Events pages are not fitting the width of the page.

*Images are included
![img_8887](https://cloud.githubusercontent.com/assets/10854834/14330974/24e85968-fc11-11e5-861d-dd77a4189001.PNG)
![img_8890](https://cloud.githubusercontent.com/assets/10854834/14330975/24eb29c2-fc11-11e5-9540-384d48b7de65.PNG)
![img_8891](https://cloud.githubusercontent.com/assets/10854834/14330976/24eb2aa8-fc11-11e5-9dc4-d30603d5ddf8.PNG)
![img_8892](https://cloud.githubusercontent.com/assets/10854834/14330977/24eb79a4-fc11-11e5-95d6-3d8ec04e76bf.PNG)
![img_8894](https://cloud.githubusercontent.com/assets/10854834/14330979/24ed696c-fc11-11e5-9cd7-b41fa47a9efe.PNG)
![img_8895](https://cloud.githubusercontent.com/assets/10854834/14330978/24ed736c-fc11-11e5-8ce3-eee938f7948a.PNG)
![img_8896](https://cloud.githubusercontent.com/assets/10854834/14330980/24f5777e-fc11-11e5-8c2d-a179eb36f2f2.PNG)
![img_8897](https://cloud.githubusercontent.com/assets/10854834/14330982/24fa07e4-fc11-11e5-824f-b363d809d678.PNG)
![img_8898](https://cloud.githubusercontent.com/assets/10854834/14330981/24f8d4aa-fc11-11e5-9b33-7a96578a4055.PNG)

**Comment by hemantcci** [comment]
Hey Cassie, I am not able to see this issue on my phone and desktop. Can you try refreshing the page and clearing the cache from browser and let me know
